name: 'Deploy Report Service'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
jobs:
  deploy-staging:
    environment: staging
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Action checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["jitsecurity/serverless-deployment-github-action@main"]'
          checkout_base_path: ./.github/actions
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}

      # the custom private action will be available on the job's workspace
      - name: 'running sls deploy'
        uses: ./.github/actions/serverless-deployment-github-action
        with:
          EPSAGON_TOKEN: ${{ secrets.EPSAGON_TOKEN }}
          SERVICE_NAME: report-service
          STAGE: staging
          PIP_SSH_KEY: ${{ secrets.DEPLOY_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          GITHUB_EVENT: '${{ toJSON(github) }}'

  e2e-staging:
    needs: [ deploy-staging ]
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: jitsecurity/jit-e2e
          ref: main
          token: ${{ secrets.PULL_KEY }}
          path: ./.github/actions/jit-e2e
      - name: Run E2E test
        id: e2etest
        uses: ./.github/actions/jit-e2e
        with:
          github_token: ${{ secrets.PULL_KEY }}
          stage: staging
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          GITHUB_EVENT: '${{ toJSON(github) }}'
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}

  deploy-prod:
    environment: prod
    needs: [ deploy-staging, e2e-staging ]
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Action checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["jitsecurity/serverless-deployment-github-action@main"]'
          checkout_base_path: ./.github/actions
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}

      # the custom private action will be available on the job's workspace
      - name: 'running sls deploy'
        uses: ./.github/actions/serverless-deployment-github-action
        with:
          EPSAGON_TOKEN: ${{ secrets.EPSAGON_TOKEN }}
          SERVICE_NAME: report-service
          STAGE: prod
          PIP_SSH_KEY: ${{ secrets.DEPLOY_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          GITHUB_EVENT: '${{ toJSON(github) }}'
